---
title: "Explore Gutenberg: Harvard Classics"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    theme: 
      version: 5
      bootswatch: minty
    source_code: embed 
---

```{r global, include=FALSE}
if(require(pacman)==F) install.packages('pacman')
pacman::p_load(flexdashboard, tidyverse, plotly, magrittr, shiny, bslib, RColorBrewer)
theme_set(theme_minimal())

my_palette = c("#B3CDE3", "#FBB4AE", "#CCEBC5")

load(url('https://github.com/linhtran304/STA_404/raw/main/just_classics/processed_classics.RData'))

```

Bookshelf
===
Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
types = c("Genres" = "genre", "Publications" = "title", "Authors" = "author")
selectInput('bookshelf', strong('Select a bookshelf to explore'), choices=unique(na.omit(data$gutenberg_bookshelf)), 
            selected = unique(data$gutenberg_bookshelf)[1])

radioButtons('type', strong('See popularity by:'), 
             choices = types)

sliderInput('top',strong('View top:'),
            min=2,max=20,step=1,value=10)

checkboxInput('color', strong('Color-code the data points'), value = F)
```

Column {.tabset .tabset-fade}
-------------------------------------
### Popularity

```{r}
selected_bookshelf <- reactive({
  
  if (input$type == "genre") {
    bookshelf_genres |> 
      filter(gutenberg_bookshelf == input$bookshelf) |> 
      ungroup() |> 
      slice_max(total_downloads, n=input$top)
    
  } else if (input$type == "author") {
    bookshelf_authors |> 
      filter(gutenberg_bookshelf == input$bookshelf) |> 
      ungroup() |> 
      slice_max(total_downloads, n=input$top)

  }
  
  else {
    data |> 
      filter(gutenberg_bookshelf == input$bookshelf) |> 
      rename(total_downloads = downloads_30_days) |> 
      slice_max(total_downloads, n=input$top)
  }
  
})

renderPlotly({
  
  bs_plot = ggplot(selected_bookshelf(), aes_string("total_downloads", paste0("reorder(",input$type,",total_downloads)")), color='grey50') + 
      geom_col(fill='#f3969a') + 
      theme(axis.title = element_blank()) +
      scale_y_discrete(labels = function(x) str_wrap(x, width = 40)) +
      labs(title = str_c("Trending: Top", input$top, names(types[which(types ==input$type)]), "in", input$bookshelf, sep=" "),
           subtitle = "by total number of downloads\nin the last 30 days")
    
          
  plotly::ggplotly(bs_plot)
  
})


```

### Sentiment vs. Popularity

```{r}
rela_df <- reactive({
  data |> 
    filter(gutenberg_bookshelf == input$bookshelf) |>
    ungroup()
    
})


renderPlotly({
  
  if (input$color == T) {
    
    plot_cor = ggplot(rela_df(), aes_string("net_bing", "downloads_30_days", color=input$type)) +
      geom_point(alpha=0.7)
    
  }
  
  else {
    plot_cor = ggplot(rela_df(), aes_string("net_bing", "downloads_30_days")) +
      geom_point(alpha=0.7, color = '#78c2ad')
    
  }
  plot_cor = plot_cor +
      labs(y = "Number of Downloads in the last 30 days",
           x = "Overall Sentiment",
           title = str_c("Sentiment vs. Popularity for", input$bookshelf, sep=" "))+
    theme(legend.position='none')
  
   plotly::ggplotly(plot_cor)
  
   
  
})
```


Genres
===
Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
types_2 = c("Publications" = "title", "Authors" = "author")
selectInput('genres', strong('Select a genre to explore'), choices=unique(na.omit(data$genre)), 
            selected = unique(data$genre)[1])

radioButtons('type_2', strong('See popularity by:'), 
             choices = types_2)

sliderInput('top_2',strong('View top:'),
            min=2,max=20,step=1,value=10)

checkboxInput('color2', strong('Color-code the data points'), value = F)
```

Column {.tabset .tabset-fade}
-------------------------------------
### Popularity

```{r}
selected_genre <- reactive({
  
  if (input$type_2 == "author") {
    genres_authors |> 
      filter(genre == input$genres) |> 
      ungroup() |> 
      slice_max(total_downloads, n=input$top_2)

  }
  
  else {
    data |> 
      filter(genre == input$genres) |> 
      rename(total_downloads = downloads_30_days) |> 
      slice_max(total_downloads, n=input$top_2)
  }
  
})

renderPlotly({
  
  gr_plot = ggplot(selected_genre(), aes_string("total_downloads", paste0("reorder(",input$type_2,",total_downloads)")), color='grey50') + 
      geom_col(fill='#f3969a') + 
      theme(axis.title = element_blank()) +
      scale_y_discrete(labels = function(x) str_wrap(x, width = 40)) +
      labs(title = str_c("Trending: Top", input$top_2, names(types_2[which(types_2 ==input$type_2)]), "in", input$genres, sep=" "),
           subtitle = "by total number of downloads\nin the last 30 days")
    
          
  plotly::ggplotly(gr_plot)
  
})


```

### Sentiment vs. Popularity

```{r}
rela_df_2 <- reactive({
  data |> 
    filter(genre == input$genres) |>
    ungroup()
    
})


renderPlotly({
  if (input$color == T){
    plot_cor_2 = ggplot(rela_df_2(), aes_string("net_bing", "downloads_30_days", color=input$type_2)) +
      geom_point(alpha=0.7)
  }
  
  else {
    plot_cor_2 = ggplot(rela_df_2(), aes_string("net_bing", "downloads_30_days")) +
      geom_point(alpha=0.7, color = '#78c2ad')
    
  }
  
  plot_cor_2 = plot_cor_2 +
      labs(y = "Number of Downloads in the last 30 days",
           x = "Overall Sentiment",
           title = str_c("Sentiment vs. Popularity for", input$genres, sep=" "))+
    theme(legend.position='none')
  
   plotly::ggplotly(plot_cor_2)
  
})
```


Author {data-orientation=rows}
===

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput('authorSearch', strong('Search for an author here'), 
            choices = unique(na.omit(data$author)),
            selected = unique(data$author)[27])

```


Row {data-height=100}
-----------------------------------------------------------------------

```{r}
selected_author_summary = reactive({
  author_summary |> 
    filter(author == input$authorSearch)
})
```

### Genres

```{r}
renderValueBox({
  df = selected_author_summary()
  genres <- df$total_genres
  valueBox(genres, 
           icon = "fa-pencil",
           color = ifelse(genres < 3, "danger", 
                          ifelse(genres < 6, "warning", "success")))
})
```

### Publications 

```{r}
renderValueBox({
  df = selected_author_summary()
  books <- df$total_books
  valueBox(books, 
           icon = "ion-ios-book",
           color = ifelse(books < 5, "danger", 
                          ifelse(books < 10, "warning", "success")))
})
```

### Downloads in the last 30 days

```{r}
renderValueBox({
  df = selected_author_summary()
  downloads <- df$total_downloads
  valueBox(downloads, 
           icon = "ion-android-download",
           color = ifelse(downloads < 500, "danger", 
                          ifelse(downloads < 1500, "warning", "success")))
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### Top Genres

```{r}
selected_author <- reactive({
  author_summary_by_genres |> 
    filter(author == input$authorSearch) |> 
    slice_max(total_pub, n=5)
})

renderPlotly({
  
  genres_plot = ggplot(selected_author(), aes(total_pub, genre, text=paste0("Total Publications: ", total_pub, "\nGenre: ",genre)), color='grey50') + 
      geom_col(fill='#6cc3d5') + 
      theme(axis.title = element_blank()) +
      scale_y_discrete(labels = function(x) str_wrap(x, width = 15)) +
      labs(title = paste0("Top Genres of ", input$authorSearch),
           subtitle = "by number of publications")
    
          
  plotly::ggplotly(genres_plot, tooltip = 'text')
    
})

```


### Sentiment
    
```{r}
sentiment <- reactive({
  data |> 
    filter(author == input$authorSearch) |> 
    slice_max(downloads_30_days, n=3) |> 
    unnest(cols = c(index, bing_positive, bing_negative, bing_overall)) |> 
    group_by(gutenberg_id)
})

renderPlotly({
  
  sentiment_plot = ggplot(sentiment(), 
                          aes(index, bing_overall, fill = title, 
                              text = paste0("Index: ", index, "\nOverall Sentiment: ",bing_overall))) +
        geom_col(show.legend = FALSE) +
        facet_wrap(~title, nrow = 1, scales = "free_x",
                   labeller = labeller(title = label_wrap_gen(width = 45))) +
        theme(legend.position = 'none',
              axis.title = element_blank()) +
        scale_fill_manual(values = my_palette)
        #labs(title = "Sentiment over the course of top popular book(s)")
    
   
  plotly::ggplotly(sentiment_plot, tooltip = 'text')
  
})

```


### Details

```{r}
detail_table <- reactive({
  data |> 
    filter(author == input$authorSearch) |> 
    mutate(language = str_to_upper(language)) |> 
    select("Title" = title, "Genre" = genre, 
           "Downloads in the last 30 days" = downloads_30_days,
           "Language" = language)

})

shiny::renderTable({
  detail_table()
}, digits = 0)
    
```

